### ISSUE TITLE
请求开放同步状态数据的跨域访问

### ISSUE THREAD

**Issue by ZenithalHourlyRate** [PKUOSC/Mirror-Web#2]
同步状态数据的 url 是 https://mirrors.pku.edu.cn/monitor/status ，该数据也可用于其他项目（例如 [mirrorz](https://mirrorz.org)），故请求开放其跨域访问，或者几个特定站的跨域访问。

具体方法为添加 `Access-Control-Allow-Origin: *` 的头或者（在`referer: https://mirrorz.org/`时）添加 `Access-Control-Allow-Origin: https://mirrorz.org`

另：注意到贵站的其余状态数据（流量，磁盘占用等）已经开放跨域访问，这些数据可能被其他项目（包括 mirrorz）使用。

**Comment by JeremyGuo** [comment]
同步数据的跨域已经开放，其他状态数据之前没有开放因为还在开发，已经解决，感谢。

**Comment by ZenithalHourlyRate** [comment]
参考 https://mirrorz.org/site/PKU 

同时建议将该 issue 移动到 github.com/pkuosc/issues 中

**Comment by JeremyGuo** [comment]
> 参考 https://mirrorz.org/site/PKU
> 
> 同时建议将该 issue 移动到 github.com/pkuosc/issues 中

已经移动，感谢（好耶

**Comment by ZenithalHourlyRate** [comment]
似乎还没有移动过去。

磁盘状态的CORS似乎设置有点问题：
参考
![Screenshot2021-03-19-16:58:07](https://user-images.githubusercontent.com/19512674/111756849-a3a76400-88d5-11eb-90b3-5894539001dc.png)
![Screenshot2021-03-19-16:57:39](https://user-images.githubusercontent.com/19512674/111756855-a5712780-88d5-11eb-94e2-9c080a5ec2d8.png)

**Comment by JeremyGuo** [comment]
https://mirrors.pku.edu.cn/monitor/status应该是允许跨域的
（突然理解到，原来mirrorz需要磁盘数据，我还以为是建议我关掉（捂脸

**Comment by JeremyGuo** [comment]
我想现在应该没有问题了（好耶
