### ISSUE TITLE
Responsibility issues on mobile platforms

### ISSUE THREAD

**Issue by shankerwangmiao** [PKUOSC/Mirror-Web#4]
![IMAGE 2021-08-23 10:54:32](https://user-images.githubusercontent.com/6825907/130383611-1f150d19-3421-4c28-a8c2-c648b49614fa.jpg)

**Comment by abc1763613206** [comment]
![IMG_20210823_105613_893](https://user-images.githubusercontent.com/30773956/130383851-79516b46-962e-4062-82ea-ccbc8f0e776a.jpg)
参考

**Comment by JeremyGuo** [comment]
不好意思，我们并没有针对移动端做优化的后续计划，因为镜像站在手机上使用的场景我们认为这是不太会出现的
